[tool.poetry]
name = "scrapshy"
version = "1.0.0"
description = ""
authors = ["WorkWithDante <dantedevenir@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.4"
selenium = "4.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"